### ISSUE TITLE
Small view: Receive screen. Changes in address flow (add max. anon set)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#80]
1) Add block "Advanced" (closed by default) and place there Maximum anonymity switcher. https://zpl.io/aX78Pgl
![image](https://user-images.githubusercontent.com/47353570/131031369-d9470711-b8da-4ac3-9050-e3ca1e4eb5c6.png)

2) Switcher default position is OFF.
Off = tx will be Regular (it is combined address - online + offline addresses)
On = tx will be Maximum anonymity set

3) When Switcher is OFF. The comment was also updated. https://zpl.io/aX78Pgl
![image](https://user-images.githubusercontent.com/47353570/131344188-99210c96-bc14-4c85-9f4d-4223d11fe56d.png)

4) When Switcher is ON - place the comment "Transaction can last at most 72 hours. Min transaction fee is 0.01 BEAM."
Add "(Maximum anonymity)" next to the ADDRESS https://zpl.io/aMXzQEm
![image](https://user-images.githubusercontent.com/47353570/131344260-717433b4-3bb0-4fc3-9393-6b68f3661d11.png)

5) When Switcher is ON - place the comment "Transaction can last indefinitely. Min transaction fee is 0.01 BEAM." The comment was updated a bit. https://zpl.io/VOygj4k
"Can last indefinitely" - depends on Lock time setting (No limit) in Privicy settings (https://zpl.io/V154reX )
![image](https://user-images.githubusercontent.com/47353570/131344346-ec665e6c-62ea-4767-819d-95b2048373e8.png)

6) Regular address details. Show full only address itself. Online (SBBS) address - always show begin and end of the address. https://zpl.io/aXyoEOP
![image](https://user-images.githubusercontent.com/47353570/131031940-051afb10-130d-4224-9e43-9ad7d4ce5b30.png)

7) Address details with max anonymity set https://zpl.io/aBPl6Qq
![image](https://user-images.githubusercontent.com/47353570/131177618-f545240d-013f-40ac-bab1-260759b85435.png)

8) QR regular. Comment was updated. https://zpl.io/bW8JqwM
![image](https://user-images.githubusercontent.com/47353570/131032207-62997cc1-4a75-4f60-9c33-8cd73aeb3f5e.png)

9) QR max anonymity. https://zpl.io/bJL3zo9 and https://zpl.io/bleWyKD
![image](https://user-images.githubusercontent.com/47353570/131344572-c6579cb3-0c05-45b7-88ae-0937b15fa9d7.png)

![image](https://user-images.githubusercontent.com/47353570/131344523-6adc6e6d-d232-42da-ad0c-72f2330bb6db.png)

10) Add toast bar after evry copy action (on icon "copy", on button "copy and close")
![image](https://user-images.githubusercontent.com/47353570/131032606-f30834d8-4119-46b8-a923-e61f7869296c.png)

**Comment by kovaletskaterina** [comment]
Receive screen
Need to add the "Address details" and QR-code button and "Comment" block on the receive screen.

3. The field "amount" should have the same title as on the design ("requested amount (optional").
- The comment "To ensure a better privacy, the new address is generated every time." shouldn't be shown.
4. According to the design, when the switcher on the "ADVANCED" block is on, the comment should be "Transaction can last at most 72 hours. Min transaction fee is 0.01 BEAM." instead of "Transaction can last indefinitely. Min transaction fee is 0.01 BEAM." if the longest transaction time for Maximum anonymity is up to 72 hours.
- When the switcher on the "ADVANCED" block is on, "(Maximum anonymity)" next to the ADDRESS as on the design should be added.
6. The "regular address details" screen should be added.
7. The "Address details with maximum anonymity set" screen should be added. The screen name should be "Maximum anonymity".

8-9. The QR-code pop-ups for the addresses as on the designs should be added.
10. The toast bar after every copy action (on icon "copy", on button "copy and close") should be added.

**Comment by kovaletskaterina** [comment]
The text on the QR-code pop-up for the address with maximum anonymity set should be changed to "Transaction can last at most 72 hours. Min transaction fee is 0.01 BEAM." or "Transaction can last indefinitely. Min transaction fee is 0.01 BEAM." according to the designs https://zpl.io/bJL3zo9 and https://zpl.io/bleWyKD

![image](https://user-images.githubusercontent.com/83376495/150789973-4dd769f4-5861-4350-83e6-05b161bfc390.png)

**Comment by kovaletskaterina** [comment]
Checked
